### ISSUE TITLE
API / Data Source

### ISSUE THREAD

**Issue by Djminisite06** [djmckee/miniature-adventure#1]
Out of curiosity was a data source ever identified for this data?

One isn't immediately apparent in the code that I can see?

If so, what is it?

**Comment by djmckee** [comment]
The app scrapes the HTML from the Arriva live bus data web pages to retrieve the data.

It's very quick and dirty but it was a 'made in an hour' kinda hack.

Should be suitably apparent in the `reloadData` method here... https://github.com/djmckee/miniature-adventure/blob/master/BusWatch%20WatchKit%20Extension/InterfaceController.m#L41 😄
